eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8000
spring:
  application:
    name: currencies
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5050/currencies
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


management:
  tracing:
    sampling:
      probability: 1.0
