eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: films
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/films/**
        - id: screenings
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/screenings/**
        - id: currencies
          uri: http://localhost:8000
          predicates:
              - Path=/api/v1/codes/**
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/users/**
        - id: emailSender
          uri: http://localhost:8022
          predicates:
            - Path=/api/v1/send/**
        - id: tickets
          uri: http://localhost:9010
          predicates:
            - Path=/api/v1/booking/**
management:
  tracing:
    sampling:
      probability: 1.0
