eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: films
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/films/**
        - id: screenings
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/screenings/**

management:
  tracing:
    sampling:
      probability: 1.0
