eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8060
spring:
  application:
    name: screenings
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5100/screenings
    username: postgres
    password: password
  liquibase:
    change-log: classpath:liquibase-changeLog.xml
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    films-url: http://localhost:8070/api/v1/films

management:
  tracing:
    sampling:
      probability: 1.0



