eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 9010
spring:
  application:
    name: tickets
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5555/tickets
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    screenings-url: http://localhost:8060/api/v1/screenings
    users-url: http://localhost:8090/api/v1/users
    emailSender-url: http://localhost:8022/api/v1
    currencies-url: http://localhost:8000/api/v1/codes

management:
  tracing:
    sampling:
      probability: 1.0
